// Generated by script/generate_nori.py from Support/Nori/design.json. Do not edit.
import CoreGraphics

enum NoriGeometry {
    static let canvas: CGFloat = 256
    static let anchor = CGPoint(x: 132, y: 218)
    static let eyes: [CGPoint] = [CGPoint(x: 119, y: 113), CGPoint(x: 182, y: 106)]
    static let eyeWidth: CGFloat = 18
    static let eyeHeight: CGFloat = 34
    static let eyeTilt: CGFloat = -10 * .pi / 180
    static let body: UInt32 = 0xBFEAF2
    static let ink: UInt32 = 0x10283F
    static let ribbonBlue: UInt32 = 0x69C7DD
    static let ribbonGold: UInt32 = 0xF2C66D
    static let ribbonLilac: UInt32 = 0xB8A7DF
    static let ribbonFail: UInt32 = 0xE56672
    static let ribbonSuccess: UInt32 = 0x5FC98A
    static let blush: UInt32 = 0xF4A6B8
    static func bodyPath() -> CGPath {
        let path = CGMutablePath()
        path.move(to: CGPoint(x: 72, y: 218))
        path.addCurve(to: CGPoint(x: 29, y: 150), control1: CGPoint(x: 36, y: 209), control2: CGPoint(x: 25, y: 186))
        path.addCurve(to: CGPoint(x: 91, y: 43), control1: CGPoint(x: 34, y: 105), control2: CGPoint(x: 56, y: 67))
        path.addCurve(to: CGPoint(x: 199, y: 21), control1: CGPoint(x: 126, y: 18), control2: CGPoint(x: 171, y: 8))
        path.addCurve(to: CGPoint(x: 235, y: 127), control1: CGPoint(x: 225, y: 34), control2: CGPoint(x: 232, y: 82))
        path.addCurve(to: CGPoint(x: 209, y: 204), control1: CGPoint(x: 238, y: 173), control2: CGPoint(x: 235, y: 194))
        path.addCurve(to: CGPoint(x: 72, y: 218), control1: CGPoint(x: 174, y: 218), control2: CGPoint(x: 119, y: 228))
        path.closeSubpath()
        return path
    }
}
