#!/usr/bin/env python3
"""Generate editable SVGs and native geometry from the approved Nori vector master.
No image dependencies. Run from any directory; only owned generated files change.
"""
import json
from nori_scenes import SCENE_LABELS, SCENE_RULES, scene_css, working_scene, extra_scene
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'SimpleMole/Support/Nori'
d = json.loads((OUT / 'design.json').read_text())
colors = d['colors']
path = ' '.join(' '.join(map(str, c)) for c in d['body'])
body = f'<path d="{path}" fill="#{colors["body"]}"/>'
eyes = ''.join(f'<g transform="translate({e["x"]} {e["y"]}) rotate({d["eyeTilt"]})"><g class="eyelid"><rect x="{-d["eyeWidth"]/2:g}" y="{-d["eyeHeight"]/2:g}" width="{d["eyeWidth"]}" height="{d["eyeHeight"]}" rx="{d["eyeWidth"]/2:g}" fill="#{colors["ink"]}"/></g></g>' for e in d['eyes'])
figure = f'<g class="jelly">{body}<g class="gaze">{eyes}</g></g>'
styles = '''
:root {color-scheme:light dark; background:transparent}
.jelly {transform-origin:132px 218px}
.eyelid {transform-origin:0 0}
.gaze {transform-origin:145px 110px}
@keyframes blink {0%,43%,49%,100%{transform:scaleY(1)}46%{transform:scaleY(.08)}}
@keyframes work {0%,100%{transform:translateY(0) scale(1,1)}25%{transform:translateY(0) scale(1.055,.945)}55%{transform:translateY(-3px) scale(.96,1.04)}80%{transform:translateY(0) scale(1.025,.975)}}
@keyframes workGaze {0%,100%{transform:translateX(-4px)}50%{transform:translateX(4px)}}
@keyframes celebrate {0%,100%{transform:translateY(0) scale(1)}15%{transform:scale(1.12,.88)}38%{transform:translateY(-3px) scale(.965,1.035)}65%{transform:scale(1.07,.93)}82%{transform:scale(.98,1.02)}}
'''
# Static is the single resting placeholder for every tab before a task starts:
# the body holds still and only the eyes blink.
rules = {
 'static': '.eyelid{animation:blink 4.2s ease-in-out infinite}',
 'working': '.jelly{animation:work 1.35s ease-in-out infinite}.gaze{animation:workGaze 2.7s ease-in-out infinite}.eyelid{animation:blink 5.4s ease-in-out infinite}',
 'success': '.jelly{animation:celebrate 1.4s ease-in-out 1}.gaze{animation:nori-lookBadge 1.9s ease-in-out 1 both}.eyelid{animation:nori-happy 1.9s ease-in-out 1 both}',
 'attention': '.jelly{animation:nori-sad 1.9s ease-in-out 1 both}.gaze{animation:nori-lookBadge 1.9s ease-in-out 1 both}',
}
labels = {'static':'静态','working':'工作中','success':'成功','attention':'失败'}
rules.update(SCENE_RULES)
labels.update(SCENE_LABELS)
styles += scene_css(colors)
# Reduced motion keeps only the resting figure; the orbit props disappear so
# a frozen half-drawn ring never reads as an error.
reduced = ('\n@media(prefers-reduced-motion:reduce){*{animation:none!important}'
           '.steam,.orbit-prop{display:none}}')
for name, rule in rules.items():
 css = styles + rule + reduced
 scene = working_scene(figure, colors) if name == 'working' else extra_scene(name, figure, colors, body, eyes)
 svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256" role="img" aria-labelledby="nori-{name}-title">
<title id="nori-{name}-title">Nori · {labels[name]}</title>
<style>{css}</style>
{scene}
</svg>
'''
 (OUT / 'Animations' / f'nori-{name}.svg').write_text(svg)
for retired in ('idle', 'bored', 'mirror', 'analyzing', 'blink', 'inspecting', 'uninstalling'):
 (OUT / 'Animations' / f'nori-{retired}.svg').unlink(missing_ok=True)
(OUT / 'Nori.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">{figure}</svg>\n')
# The full-bleed, UNMASKED foreground for Icon Composer; masking belongs to macOS.
(OUT / 'AppIcon.icon/Assets/Nori.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><g transform="translate(92 104) scale(3.25)">{figure}</g></svg>\n')
# Native geometry is generated, so SVG and SwiftUI cannot quietly drift apart.
lines=['// Generated by script/generate_nori.py from Support/Nori/design.json. Do not edit.', 'import CoreGraphics', '', 'enum NoriGeometry {', f'    static let canvas: CGFloat = {d["canvas"]}', f'    static let anchor = CGPoint(x: {d["anchor"]["x"]}, y: {d["anchor"]["y"]})', '    static let eyes: [CGPoint] = [' + ', '.join(f'CGPoint(x: {e["x"]}, y: {e["y"]})' for e in d['eyes']) + ']', f'    static let eyeWidth: CGFloat = {d["eyeWidth"]}', f'    static let eyeHeight: CGFloat = {d["eyeHeight"]}', f'    static let eyeTilt: CGFloat = {d["eyeTilt"]} * .pi / 180']
for key,value in colors.items():lines.append(f'    static let {key}: UInt32 = 0x{value}')
lines += ['    static func bodyPath() -> CGPath {', '        let path = CGMutablePath()']
for c in d['body']:
 if c[0]=='M':lines.append(f'        path.move(to: CGPoint(x: {c[1]}, y: {c[2]}))')
 elif c[0]=='C':lines.append(f'        path.addCurve(to: CGPoint(x: {c[5]}, y: {c[6]}), control1: CGPoint(x: {c[1]}, y: {c[2]}), control2: CGPoint(x: {c[3]}, y: {c[4]}))')
 else:lines.append('        path.closeSubpath()')
lines += ['        return path','    }','}']
(ROOT / 'SimpleMole/Views/NoriGeometry.swift').write_text('\n'.join(lines)+'\n')
print(f'Generated Nori vector source, {len(rules)} SVG states and shared Swift geometry.')
